# clones a git repo,
# do whatever you want with it with a script
#
# Now with NPM, and nodejs !
#
# VERSION               1.0.1
#
FROM picoded/git-cloner-base:latest

# This is in accordance to : https://nodejs.org/en/download/package-manager/
RUN apt-get update; \
	apt-get install -y npm && \
	apt-get install -y nodejs;
