# ubuntu-python
#
# VERSION               0.0.1
#
# Also sets language to en_US.UTF-8 by default
#
FROM picoded/ubuntu-python
MAINTAINER Eugene Cheah <picoded@socialoctet.com>

RUN git clone https://github.com/picoded/httpbin.git

